apiVersion: apps/v1beta1
kind: Deployment
metadata:   
  name: nginx
spec:
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.16-alpine
        command: ["/bin/sh","-c","touch /usr/share/nginx/html/index.php; nginx -g 'daemon off;'"]
        ports:
        - containerPort: 80

        volumeMounts:
        - mountPath: /etc/nginx/conf.d #Local onde o volume vai ser criado o volume
          name: nginx-conf #Nome do volume que será chamado para ser montado
          readOnly: true

      volumes:
      - name: nginx-conf #Nome do volume que vai ser montado
        configMap:
          name: nginx-conf #Nome dado no name do arquivo configmap.yaml
          items:
            - key: nginx.conf #Nome da chave dado no data do arquivo configmap.yaml
              path: nginx.conf #Nome do arquivo que será montado, nesse caso dentro da pasta conf.d
           